import './style.css'; import { groups, removeGroup, prefs, savePrefs } from '../../src/storage'; import { key, type RestoreTab } from '../../src/models'; import { uaProfiles } from '../../src/ua';
const el = (id: string) => document.getElementById(id) as HTMLInputElement;
const toggles = [['dark', 'darkDomains'], ['autoplay', 'autoplayAllowlist'], ['consent', 'consentDomains']] as const;
let currentCookies: chrome.cookies.Cookie[] = [];
// The manager runs as a real side panel in Chrome, but as an ordinary tab where the
// sidePanel API is missing (Opera) — there the active tab is this page, so skip our own
// pages and fall back to the most recently used tab.
async function tab() { const tabs = (await chrome.tabs.query({ currentWindow: true })).filter(t => t.url && !t.url.startsWith(location.origin)); return tabs.find(t => t.active) ?? tabs.sort((a, b) => ((b as { lastAccessed?: number }).lastAccessed ?? 0) - ((a as { lastAccessed?: number }).lastAccessed ?? 0))[0]; }
const host = (t?: chrome.tabs.Tab) => { try { return new URL(t!.url!).hostname; } catch { return ''; } };
const show = (caption: string, value: unknown) => { el('caption').textContent = caption; el('inspect').textContent = JSON.stringify(value, null, 2); };
async function render() { const list = await groups(); el('groups').innerHTML = list.map(g => `<article><div class="title"><b>${escape(g.name)}</b><span class="count">${g.tabs.length} tabs</span></div>${g.tags.length ? `<div>${g.tags.map(t => `<span class="chip">${escape(t)}</span>`).join(' ')}</div>` : ''}<div class="actions"><button class="btn" data-id="${g.id}">Open</button><button class="btn btn-danger" data-delete="${g.id}">Delete</button></div></article>`).join('') || '<p class="hint">No saved groups yet.</p>'; document.querySelectorAll('[data-id]').forEach(b => b.addEventListener('click', async () => { const g = list.find(x => x.id === (b as HTMLElement).dataset.id)!; for (const t of g.tabs) await chrome.tabs.create({ url: t.url, active: false }); })); document.querySelectorAll('[data-delete]').forEach(b => b.addEventListener('click', async () => { if (confirm('Delete this saved group?')) { await removeGroup((b as HTMLElement).dataset.delete!); render(); } })); }
const escape = (s: string) => s.replace(/[&<>"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c]!));
(async () => { const p = await prefs(); el('cleaner').checked=p.cleanerEnabled; el('minutes').value=String(p.cleanerMinutes); el('exclude').value=p.excludedDomains.join(','); const domain=host(await tab()); el('target').textContent = domain ? `Acting on ${domain} — applies on next reload.` : 'No page tab found.'; for (const [id, field] of toggles) el(id).setAttribute('aria-pressed', String(p[field].includes(domain))); render(); })();
el('trace').onclick = async () => { const t = await tab(); show('Redirect chain', await chrome.runtime.sendMessage({ type:'redirects', tabId:t.id })); };
for (const [id, field] of toggles) el(id).onclick = async () => { const t=await tab(); const enabled=await chrome.runtime.sendMessage({type:'toggle-pref', field, domain:host(t)}); el(id).setAttribute('aria-pressed', String(enabled)); };
el('cookies').onclick = async () => { const t=await tab(); currentCookies = await chrome.runtime.sendMessage({ type:'cookies', windowId:t.windowId }); show(`Cookies in this window (${currentCookies.length})`, currentCookies); };
el('ua').onchange = async () => { const t=await tab(), name=el('ua').value as keyof typeof uaProfiles; if(name) await chrome.runtime.sendMessage({ type:'ua', windowId:t.windowId, domain:host(t), value:uaProfiles[name] }); };
el('prefs').onclick = async () => { await savePrefs({ cleanerEnabled:el('cleaner').checked, cleanerMinutes:Number(el('minutes').value)||60, excludedDomains:el('exclude').value.split(',').map(x=>x.trim()).filter(Boolean) }); el('saved').textContent='Saved.'; setTimeout(()=>{ el('saved').textContent=''; }, 2000); };
el('restore').onclick = async () => { const saved=((await chrome.storage.session.get(key.restore))[key.restore]??[]) as RestoreTab[]; if(saved[0]) { const t=await tab(); await chrome.runtime.sendMessage({type:'restore', windowId:t.windowId, tab:saved[0]}); } };
el('export').onclick = () => { el('json').value=JSON.stringify(currentCookies, null, 2); };
el('import').onclick = async () => { if (!confirm('Import overwrites matching cookies in your Chrome profile. Continue?')) return; const r=await chrome.runtime.sendMessage({type:'import-cookies',json:el('json').value}); if(r?.error) alert(r.error); else alert('Imported.'); };
