import './style.css'; import { groups, removeGroup, prefs, savePrefs } from '../../src/storage'; import { key, type RestoreTab } from '../../src/models'; import { uaProfiles } from '../../src/ua';
const el = (id: string) => document.getElementById(id) as HTMLInputElement;
let currentCookies: chrome.cookies.Cookie[] = [];
async function tab() { return (await chrome.tabs.query({ active: true, currentWindow: true }))[0]; }
async function render() { const list = await groups(); el('groups').innerHTML = list.map(g => `<article><b>${escape(g.name)}</b> (${g.tabs.length}) <small>${g.tags.join(', ')}</small> <button data-id="${g.id}">Open</button> <button data-delete="${g.id}">Delete</button></article>`).join('') || '<small>No saved groups.</small>'; document.querySelectorAll('[data-id]').forEach(b => b.addEventListener('click', async () => { const g = list.find(x => x.id === (b as HTMLElement).dataset.id)!; for (const t of g.tabs) await chrome.tabs.create({ url: t.url, active: false }); })); document.querySelectorAll('[data-delete]').forEach(b => b.addEventListener('click', async () => { if (confirm('Delete this saved group?')) { await removeGroup((b as HTMLElement).dataset.delete!); render(); } })); }
const escape = (s: string) => s.replace(/[&<>"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c]!));
(async () => { const p = await prefs(); el('cleaner').checked=p.cleanerEnabled; el('minutes').value=String(p.cleanerMinutes); el('exclude').value=p.excludedDomains.join(','); render(); })();
el('trace').onclick = async () => { const t = await tab(); el('inspect').textContent = JSON.stringify(await chrome.runtime.sendMessage({ type:'redirects', tabId:t.id }), null, 2); };
for (const [id, field] of [['dark','darkDomains'], ['autoplay','autoplayAllowlist'], ['consent','consentDomains']] as const) el(id).onclick = async () => { const t=await tab(); const enabled=await chrome.runtime.sendMessage({type:'toggle-pref', field, domain:new URL(t.url!).hostname}); el('inspect').textContent=`${field}: ${enabled ? 'enabled' : 'disabled'} (reload tab)`; };
el('cookies').onclick = async () => { const t=await tab(); currentCookies = await chrome.runtime.sendMessage({ type:'cookies', windowId:t.windowId }); el('inspect').textContent = JSON.stringify(currentCookies, null, 2); };
el('ua').onchange = async () => { const t=await tab(), name=el('ua').value as keyof typeof uaProfiles; if(name) await chrome.runtime.sendMessage({ type:'ua', windowId:t.windowId, domain:new URL(t.url!).hostname, value:uaProfiles[name] }); };
el('prefs').onclick = () => savePrefs({ cleanerEnabled:el('cleaner').checked, cleanerMinutes:Number(el('minutes').value)||60, excludedDomains:el('exclude').value.split(',').map(x=>x.trim()).filter(Boolean) });
el('restore').onclick = async () => { const saved=((await chrome.storage.session.get(key.restore))[key.restore]??[]) as RestoreTab[]; if(saved[0]) { const t=await tab(); await chrome.runtime.sendMessage({type:'restore', windowId:t.windowId, tab:saved[0]}); } };
el('export').onclick = () => { el('json').value=JSON.stringify(currentCookies, null, 2); };
el('import').onclick = async () => { if (!confirm('Import overwrites matching cookies in your Chrome profile. Continue?')) return; const r=await chrome.runtime.sendMessage({type:'import-cookies',json:el('json').value}); if(r?.error) alert(r.error); else alert('Imported.'); };
